// apps/react-lazy-image/src/components/HeroArticle.jsx

export default function HeroArticle({ article }) {
    if (!article) return null;

    return (
        <a
            href={`#/article/${article.id}`}
            className="block mb-6 rounded overflow-hidden shadow hover:shadow-lg transition"
        >
            <img
                src={article.imageUrl}
                alt={article.title}
                className="w-full h-64 object-cover"
                loading="lazy"
            />
            <div className="p-4 bg-white">
                <h1 className="text-2xl font-bold mb-2">{article.title}</h1>
                <p className="text-sm text-gray-600">{article.excerpt}</p>
            </div>
        </a>
    );
}

// apps/svelte-lazy-image/src/lib/HeroArticle.svelte
<script>
  export let article;

  $: hidden = !article;
</script>

{#if !hidden}
  <a
    href={`#/article/${article.id}`}
    class="block mb-6 rounded overflow-hidden shadow hover:shadow-lg transition"
  >
    <img
      src={article.imageUrl}
      alt={article.title}
      class="w-full h-64 object-cover"
      loading="lazy"
    />  
    <div class="p-4 bg-white">
      <h1 class="text-2xl font-bold mb-2">{article.title}</h1>
      <p class="text-sm text-gray-600">{article.excerpt}</p>
    </div>
  </a>
{/if}
