// apps/svelte-visibility-based-rendering/src/lib/LazyRender.svelte
<script>
    import { onMount } from "svelte";

    let visible = false;
    let el;

    onMount(() => {
        const observer = new IntersectionObserver(
            ([entry]) => {
                console.log("ENTRY:", entry.isIntersecting, entry.target);
                if (entry.isIntersecting) {
                    visible = true;
                    observer.unobserve(entry.target);
                }
            },
            {
                rootMargin: "0px", //
                threshold: 0.25, // 
            },
        );

        if (el) observer.observe(el);

        return () => {
            observer.disconnect();
        };
    });
</script>

<div
    bind:this={el}
    style="min-height: 100px; background: {visible ? 'transparent' : '#eee'};"
>
    {#if visible}
        <slot />
    {/if}
</div>

// apps/react-visibility-based-rendering/src/components/LazyRender.jsx
import { useEffect, useRef, useState } from 'react';

export default function LazyRender({ children }) {
  const [visible, setVisible] = useState(false);
  const ref = useRef();

  useEffect(() => {
    if (!ref.current) return;

    const observer = new IntersectionObserver(
      ([entry]) => {
        console.log('Intersection:', entry.isIntersecting, entry.target);
        if (entry.isIntersecting) {
          setVisible(true);
          observer.unobserve(entry.target);
        }
      },
      {
        rootMargin: '0px',
        threshold: 0.25,
      }
    );

    observer.observe(ref.current);

    return () => {
      if (ref.current) observer.unobserve(ref.current);
    };
  }, []);

  return (
    <div ref={ref} style={{ minHeight: '100px', background: visible ? 'white' : 'lightgray' }}>
      {visible ? children : null}
    </div>
  );
}
