// apps/react-code-splitting/src/pages/ArticleDetail.jsx
// src/pages/ArticleDetail.jsx
import { useEffect, useState } from 'react';
import { fetchArticleById } from '../api';

export default function ArticleDetail({ id }) {
    const [article, setArticle] = useState(null);

    useEffect(() => {
        fetchArticleById(parseInt(id)).then(setArticle);
    }, [id]);

    if (!article) {
        return <div className="p-4">Memuat data...</div>;
    }

    const published = new Date(article.publishedAt).toLocaleString('id-ID', {
        weekday: 'long',
        year: 'numeric',
        month: 'long',
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit'
    });

    return (
        <>
            <main className="max-w-3xl mx-auto p-4">
                <img
                    src={article.imageUrl}
                    alt={article.title}
                    className="w-full h-64 object-cover rounded mb-4"
                />
                <h1 className="text-3xl font-bold mb-2">{article.title}</h1>
                <p className="text-sm text-gray-500 mb-6">{published}</p>
                <p className="text-base text-gray-800 leading-relaxed whitespace-pre-line">
                    {article.content}
                </p>
            </main>
        </>
    );
}

// apps/svelte-baseline/src/pages/ArticleDetail.svelte
<script>
  import { onMount } from "svelte";
  import { fetchArticleById } from "../api";

  export let id;
  let article = null;

  onMount(async () => {
    const result = await fetchArticleById(parseInt(id));
    article = result;
  });

  const formatDate = (datetime) =>
    new Date(datetime).toLocaleString("id-ID", {
      weekday: "long",
      year: "numeric",
      month: "long",
      day: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    });
</script>

{#if !article}
  <div class="p-4">Memuat...</div>
{:else}
  <main class="max-w-3xl mx-auto p-4">
    <img
      src={article.imageUrl}
      alt={article.title}
      class="w-full h-64 object-cover rounded mb-4"
    />
    <h1 class="text-3xl font-bold mb-2">{article.title}</h1>
    <p class="text-sm text-gray-500 mb-6">{formatDate(article.publishedAt)}</p>
    <p class="text-base text-gray-800 leading-relaxed whitespace-pre-line">
      {article.content}
    </p>
  </main>
{/if}
