// apps/svelte-visibility-based-rendering/src/App.svelte
<script>
  import { onMount } from "svelte";
  import Home from "./pages/Home.svelte";
  import ArticleDetail from "./pages/ArticleDetail.svelte";
  import Header from "./lib/Header.svelte";
  import Footer from "./lib/Footer.svelte";

  let route = window.location.hash;
  let articleId = null;

  const updateRoute = () => {
    route = window.location.hash;
    const match = route.match(/^#\/article\/(\d+)$/);
    articleId = match ? match[1] : null;
  };

  onMount(() => {
    updateRoute();
    window.addEventListener("hashchange", updateRoute);
    return () => window.removeEventListener("hashchange", updateRoute);
  });
</script>

<Header />

{#if articleId}
  <ArticleDetail id={articleId} />
{:else}
  <Home />
{/if}

<Footer />

// apps/react-visibility-based-rendering/src/App.jsx
import { useEffect, useState } from 'react';
import Home from './pages/Home';
import ArticleDetail from './pages/ArticleDetail';
import Header from './components/Header';
import Footer from './components/Footer';

export default function App() {
    const [route, setRoute] = useState(window.location.hash);

    useEffect(() => {
        const handleHashChange = () => {
            setRoute(window.location.hash);
        };
        window.addEventListener('hashchange', handleHashChange);
        return () => window.removeEventListener('hashchange', handleHashChange);
    }, []);

    const match = route.match(/^#\/article\/(\d+)$/);
    const articleId = match ? match[1] : null;

    return (
        <>
            <Header />
            <main>
                {articleId ? (
                    <ArticleDetail id={articleId} />
                ) : (
                    <Home />
                )}
            </main>
            <Footer />
        </>
    );
}
